feat(content): add authors and posts
tezos-israel/tezos.co.il pull request #59
Opened 2021-06-24 14:34 UTC by Aharonla

2021-06-27 18:04 UTC, chiptus requested changes
very good. remove some old files and we can merge this.

2021-06-27 18:04 UTC, chiptus commented on data/TODO.md
> +### Add posts
remove file

2021-06-27 18:04 UTC, chiptus commented on data/blog/_categories/miscellaneous.md
> +title: 'Miscellaneous '
remove whitespace

2021-06-27 18:04 UTC, chiptus commented on data/blog/how-to-run-a-node-on-the-tezos-blockchain-part-1.md
> +#### <span style="text-decoration: underline;">**Note: This is _Part 1_ of  “How to Run a Node on the Tezos Blockchain” Series**</span>
remove html. this goes for other posts too

2021-06-27 18:04 UTC, chiptus commented on data/blog/how-to-run-a-node-on-the-tezos-blockchain-part-1.md
> +To run a node using a snapshot, please read[ part 3](https://tezos.co.il/719-2/)
remove whitespace from link
```suggestion
To run a node using a snapshot, please read [part 3](https://tezos.co.il/719-2/)
```

2021-06-27 18:04 UTC, chiptus commented on data/blog/playing-with-smartpy-smart-contracts-part-1.md
> +title: Playing with SmartPy Smart Contracts (Part 1)
we have a duplicate for this, remove the duplicate

2021-06-27 18:04 UTC, chiptus commented on data/blog/sample-post.md
>  tags:
remove this sample post

2021-06-27 21:17 UTC, Aharonla commented on data/blog/how-to-run-a-node-on-the-tezos-blockchain-part-1.md
> +#### <span style="text-decoration: underline;">**Note: This is _Part 1_ of  “How to Run a Node on the Tezos Blockchain” Series**</span>
I tried to find a different way to get an underline. this was the only way I found

2021-06-28 12:11 UTC, chiptus commented on data/blog/how-blockchain-can-help-banks-and-financing.md
> +![http://www.mnazureusergroup.com/wp-content/uploads/2018/07/f4bfd768-4990-4855-8abd-a7497678f415-300x225.jpg](https://tezos.co.il/wp-content/uploads/2020/01/anti-fraud.jpeg)
```suggestion
![Blockchain Anti-Fraud](https://tezos.co.il/wp-content/uploads/2020/01/anti-fraud.jpeg)  
```

2021-06-28 12:15 UTC, merged