style(layout): change font-family
tezos-israel/tezos.co.il pull request #95
Opened 2021-07-14 14:12 UTC by Aharonla

2021-07-14 14:44 UTC, chiptus requested changes
just one change, LGTM otherwise

2021-07-14 14:44 UTC, chiptus commented on src/components/TeamMember.js
> +    <div className="flex flex-col items-center text-tezos-blue mono p-1 lg:w-1/3 md:w-1/3 w-full mb-4">
just `mono` or `museo` doesn't do anything. I guess it's a mistake. remove it

2021-07-14 14:54 UTC, Aharonla commented on src/components/TeamMember.js
> +    <div className="flex flex-col items-center text-tezos-blue mono p-1 lg:w-1/3 md:w-1/3 w-full mb-4">
it was a mistake, removed

2021-07-19 06:25 UTC, chiptus commented
decided to close

2021-07-19 06:25 UTC, closed without merging